# Use the Bun image
FROM oven/bun:latest as development

# Set working directory
WORKDIR /app

# Copy only package manager files to install dependencies
COPY bun.lockb package.json ./

# Install dependencies (include dev dependencies)
RUN bun install

# Copy the rest of the source code
COPY . .

# Set environment to development
ENV NODE_ENV=development

# Expose the development port
EXPOSE 3000

# Run the application with hot reloading
CMD ["bun", "dev", "--watch"]
